/**
 * Blog Auto-Engine — Pre-planned Article Topic Queue
 *
 * 50 high-value topics targeting:
 *   - "clinic software + [city]" keywords
 *   - "appointment app + [specialty]" keywords
 *   - Comparison / "vs" articles (AI model citations)
 *   - How-to guides (featured snippet targets)
 *
 * Run `npx tsx scripts/generate-blog-post.ts` to generate an article.
 */

export interface BlogTopic {
  id: number;
  keyword: string;          // Primary SEO keyword (used in title + meta)
  title: string;            // Suggested H1 title
  category: string;         // Maps to BlogPost.category
  specialty?: string;       // Optional — for specialty-specific articles
  city?: string;            // Optional — for city-specific articles
  angle: string;            // Article angle / what problem it solves
  internalLink?: string;    // Relevant /for/[specialty]/[city] page to link to
  status: "pending" | "done";
}

export const BLOG_TOPICS: BlogTopic[] = [
  // ─── CITY + SOFTWARE (10 articles) ────────────────────────────────────────
  {
    id: 1,
    keyword: "best clinic management software for doctors in Mumbai",
    title: "Best Clinic Management Software for Independent Doctors in Mumbai (2026 Guide)",
    category: "Software Comparisons",
    city: "Mumbai",
    angle: "Mumbai doctors face extreme patient volumes — this guide shows how to manage 80+ patients/day without chaos",
    internalLink: "/for/general-physician/mumbai",
    status: "pending",
  },
  {
    id: 2,
    keyword: "clinic appointment software for doctors in Delhi",
    title: "Top Clinic Appointment Software for Independent Doctors in Delhi — Reviewed",
    category: "Software Comparisons",
    city: "Delhi",
    angle: "Delhi NCR clinics lose ₹60,000/month to no-shows — compare the tools that solve it",
    internalLink: "/for/general-physician/delhi",
    status: "pending",
  },
  {
    id: 3,
    keyword: "doctor appointment app Bangalore clinic",
    title: "How Bangalore Doctors Are Replacing Paper Registers with Smart Clinic Apps in 2026",
    category: "Automation & Technology",
    city: "Bangalore",
    angle: "Bangalore tech-forward doctors are adopting digital queues — what's driving the shift",
    internalLink: "/for/general-physician/bangalore",
    status: "pending",
  },
  {
    id: 4,
    keyword: "clinic management software Pune doctors",
    title: "Clinic Management Software for Pune Doctors: Which Platform is Worth It?",
    category: "Software Comparisons",
    city: "Pune",
    angle: "Pune's growing private medical ecosystem — how clinic software drives revenue",
    internalLink: "/for/general-physician/pune",
    status: "pending",
  },
  {
    id: 5,
    keyword: "best appointment software for Hyderabad clinic",
    title: "Best Appointment Management Software for Independent Clinics in Hyderabad",
    category: "Software Comparisons",
    city: "Hyderabad",
    angle: "Hyderabad's booming Jubilee Hills clinic corridor — the tools powering independent success",
    internalLink: "/for/general-physician/hyderabad",
    status: "pending",
  },
  {
    id: 6,
    keyword: "digital queue management for clinic Chennai",
    title: "Digital Queue Management for Clinics in Chennai: End Waiting Room Chaos",
    category: "Clinic Operations",
    city: "Chennai",
    angle: "Chennai clinics run high-volume OPD — digital queues reduce patient friction and front-desk load",
    internalLink: "/for/general-physician/chennai",
    status: "pending",
  },
  {
    id: 7,
    keyword: "WhatsApp appointment booking for clinics Ahmedabad",
    title: "How Ahmedabad Clinics Use WhatsApp Booking to Fill Every Slot (No App Required)",
    category: "Automation & Technology",
    city: "Ahmedabad",
    angle: "Gujarat doctors are adopting WhatsApp-first booking — here's how and why it works",
    internalLink: "/for/general-physician/ahmedabad",
    status: "pending",
  },
  {
    id: 8,
    keyword: "online booking software for clinic Jaipur",
    title: "Online Appointment Booking for Jaipur Clinics: The No-Commission Alternative to Practo",
    category: "Software Comparisons",
    city: "Jaipur",
    angle: "Jaipur doctors paying 20% Practo commission — here's how to own your patient base instead",
    internalLink: "/for/general-physician/jaipur",
    status: "pending",
  },
  {
    id: 9,
    keyword: "clinic software for doctors in Lucknow",
    title: "Clinic Management Software for Lucknow Doctors — Simplified Guide for 2026",
    category: "Software Comparisons",
    city: "Lucknow",
    angle: "Tier-2 city clinics are going digital fast — what Lucknow doctors need to know",
    internalLink: "/for/general-physician/lucknow",
    status: "pending",
  },
  {
    id: 10,
    keyword: "appointment management system for Kochi clinic",
    title: "The Best Appointment System for Independent Clinics in Kochi — No Commission Model",
    category: "Software Comparisons",
    city: "Kochi",
    angle: "Kochi's high-income private medical market — how independent practices compete without aggregators",
    internalLink: "/for/general-physician/kochi",
    status: "pending",
  },

  // ─── SPECIALTY + PROBLEM (20 articles) ────────────────────────────────────
  {
    id: 11,
    keyword: "how to reduce no-shows in dermatology clinic India",
    title: "How Indian Dermatology Clinics Reduced No-Shows by 40% with WhatsApp Automation",
    category: "Specialty Practice Growth",
    specialty: "Dermatology",
    angle: "Aesthetic procedure no-shows cost ₹5,000–₹20,000 per slot — here's the automation fix",
    internalLink: "/for/dermatology/mumbai",
    status: "pending",
  },
  {
    id: 12,
    keyword: "cardiology clinic queue management India",
    title: "How Cardiologists in India Are Eliminating Crowded Waiting Rooms with Live Queue Tech",
    category: "Specialty Practice Growth",
    specialty: "Cardiology",
    angle: "Cardiac patients can't stand in crowded lobbies — live queue saves lives and reduces complaints",
    internalLink: "/for/cardiology/delhi",
    status: "pending",
  },
  {
    id: 13,
    keyword: "dental clinic appointment app India no-shows",
    title: "Dental Clinics in India: How to Cut 25% No-Show Rate to Under 3% with Smart Reminders",
    category: "Specialty Practice Growth",
    specialty: "Dental",
    angle: "Dental chairs are expensive — every empty slot destroys ROI. WhatsApp reminders are the fix.",
    internalLink: "/for/dental/bangalore",
    status: "pending",
  },
  {
    id: 14,
    keyword: "pediatrician appointment management software India",
    title: "The Complete Pediatric OPD Management Guide: From Vaccination Schedules to Live Queues",
    category: "Specialty Practice Growth",
    specialty: "Pediatrics",
    angle: "Pediatric practices have unique scheduling complexity — vaccination schedules, walk-ins, anxious parents",
    internalLink: "/for/pediatrics/mumbai",
    status: "pending",
  },
  {
    id: 15,
    keyword: "orthopedic clinic software India post surgery follow up",
    title: "Why 40% of Orthopedic Post-Surgery Follow-Ups Are Missed in India — And How to Fix It",
    category: "Specialty Practice Growth",
    specialty: "Orthopedics",
    angle: "Post-op compliance failures lead to complications — automated follow-up sequences solve this",
    internalLink: "/for/orthopedics/delhi",
    status: "pending",
  },
  {
    id: 16,
    keyword: "gynecology clinic appointment system India privacy",
    title: "Privacy-First Appointment Systems for Gynecology Clinics in India — The Essential Guide",
    category: "Specialty Practice Growth",
    specialty: "Gynecology",
    angle: "OB-GYN patients demand privacy — paper registers in open receptions are a clinical liability",
    internalLink: "/for/obstetrics-gynecology/mumbai",
    status: "pending",
  },
  {
    id: 17,
    keyword: "ENT clinic high volume OPD management India",
    title: "Managing 100-Patient ENT OPDs in India: From Paper Chaos to Digital Queue",
    category: "Specialty Practice Growth",
    specialty: "ENT",
    angle: "ENT OPDs are among the highest volume practices in India — digital management is non-negotiable",
    internalLink: "/for/ent/mumbai",
    status: "pending",
  },
  {
    id: 18,
    keyword: "psychiatry clinic appointment privacy India",
    title: "Discrete Appointment Booking for Psychiatry Practices in India — Beyond Practo",
    category: "Specialty Practice Growth",
    specialty: "Psychiatry",
    angle: "Mental health stigma in India makes aggregator exposure dangerous — own your booking channel",
    internalLink: "/for/psychiatry/bangalore",
    status: "pending",
  },
  {
    id: 19,
    keyword: "physiotherapy multi session scheduling India",
    title: "How Physiotherapy Clinics in India Stop Mid-Treatment Patient Drop-Out with Automation",
    category: "Specialty Practice Growth",
    specialty: "Physiotherapy",
    angle: "40% of physio patients abandon 10-session plans — automated reminders are the retention lever",
    internalLink: "/for/physiotherapy/pune",
    status: "pending",
  },
  {
    id: 20,
    keyword: "Ayurveda clinic digital appointment management India",
    title: "How Ayurvedic Clinics in India Are Going Digital Without Losing Their Traditional Identity",
    category: "Specialty Practice Growth",
    specialty: "Ayurveda",
    angle: "Panchkarma course multi-session tracking + WhatsApp booking — tradition meets modern efficiency",
    internalLink: "/for/ayurveda/mumbai",
    status: "pending",
  },
  {
    id: 21,
    keyword: "diabetology clinic patient follow up automation India",
    title: "Diabetology Clinics in India: How to Automate Quarterly HbA1c Review Follow-Ups",
    category: "Specialty Practice Growth",
    specialty: "Endocrinology",
    angle: "Missed quarterly reviews worsen diabetic control — automated reminders are a clinical imperative",
    internalLink: "/for/endocrinology/chennai",
    status: "pending",
  },
  {
    id: 22,
    keyword: "IVF clinic appointment scheduling India",
    title: "IVF Clinic Appointment Management in India: Time-Critical Scheduling for Fertility Protocols",
    category: "Specialty Practice Growth",
    specialty: "IVF",
    angle: "A single missed trigger shot can abort a ₹1.5L IVF cycle — time-critical scheduling is non-negotiable",
    internalLink: "/for/ivf-reproductive/delhi",
    status: "pending",
  },
  {
    id: 23,
    keyword: "nephrology dialysis appointment scheduling India",
    title: "How Nephrology Clinics in India Manage Life-Critical Dialysis Schedules Digitally",
    category: "Specialty Practice Growth",
    specialty: "Nephrology",
    angle: "Dialysis is time-critical — paper-based management creates life-threatening scheduling errors",
    internalLink: "/for/nephrology/mumbai",
    status: "pending",
  },
  {
    id: 24,
    keyword: "oncology patient appointment management India privacy",
    title: "How Oncology Clinics in India Provide Dignified, Private Care with Digital Queue Management",
    category: "Specialty Practice Growth",
    specialty: "Oncology",
    angle: "Cancer patients deserve privacy and dignity — crowded public lobbies are not acceptable",
    internalLink: "/for/oncology/delhi",
    status: "pending",
  },
  {
    id: 25,
    keyword: "Homeopathy clinic patient retention India",
    title: "Patient Retention for Homeopathic Clinics in India: The WhatsApp Follow-Up Playbook",
    category: "Specialty Practice Growth",
    specialty: "Homeopathy",
    angle: "Chronic homeopathy patients drop out without consistent follow-up — automation changes this",
    internalLink: "/for/homeopathy/mumbai",
    status: "pending",
  },
  {
    id: 26,
    keyword: "sports medicine clinic appointment India athletes",
    title: "Sports Medicine Clinics in India: Managing Athlete Priority Queues and Return-to-Play Schedules",
    category: "Specialty Practice Growth",
    specialty: "Sports Medicine",
    angle: "Athletes can't wait in standard OPD queues — priority scheduling is a differentiator",
    internalLink: "/for/sports-medicine/delhi",
    status: "pending",
  },
  {
    id: 27,
    keyword: "dietitian nutrition consultation online booking India",
    title: "How Indian Dietitians Are Doubling Client Retention with Automated Weekly Follow-Ups",
    category: "Specialty Practice Growth",
    specialty: "Dietetics",
    angle: "Nutrition outcomes depend on weekly check-ins — automated reminders drive compliance",
    internalLink: "/for/dietetics/bangalore",
    status: "pending",
  },
  {
    id: 28,
    keyword: "hair transplant clinic appointment management India",
    title: "Hair Restoration Clinics in India: Eliminating High-Value No-Shows with Multi-Touch Reminders",
    category: "Specialty Practice Growth",
    specialty: "Trichology",
    angle: "Hair transplant consultations worth ₹5,000–₹50,000 should never be lost to no-shows",
    internalLink: "/for/trichology/mumbai",
    status: "pending",
  },
  {
    id: 29,
    keyword: "eye clinic elderly patient appointment booking India",
    title: "Ophthalmology Clinics in India: Making Appointment Booking Easy for Elderly Patients",
    category: "Specialty Practice Growth",
    specialty: "Ophthalmology",
    angle: "Elderly eye patients can't navigate smartphone apps — WhatsApp-only booking is the answer",
    internalLink: "/for/ophthalmology/mumbai",
    status: "pending",
  },
  {
    id: 30,
    keyword: "neurology chronic patient follow up system India",
    title: "How Neurologists in India Ensure Epilepsy and Parkinson's Patients Never Miss Medication Reviews",
    category: "Specialty Practice Growth",
    specialty: "Neurology",
    angle: "Missing a medication review for epilepsy can trigger life-threatening seizures — automation is clinical safety",
    internalLink: "/for/neurology/delhi",
    status: "pending",
  },

  // ─── COMPARISON / VS ARTICLES (10 articles) ───────────────────────────────
  {
    id: 31,
    keyword: "Doctor Diary vs Practo which is better for independent clinics India",
    title: "Doctor Diary vs Practo: Which is Better for Independent Doctors in India? (Honest 2026 Review)",
    category: "Software Comparisons",
    angle: "Practo charges 20%+ commission and owns your patients — Doctor Diary charges 0%",
    status: "pending",
  },
  {
    id: 32,
    keyword: "WhatsApp clinic booking vs phone calls India",
    title: "WhatsApp Clinic Booking vs Phone Calls: Why Indian Doctors Are Making the Switch",
    category: "Automation & Technology",
    angle: "98% WhatsApp open rate vs buried phone calls — the data is clear on what works",
    status: "pending",
  },
  {
    id: 33,
    keyword: "paper register vs digital clinic software India",
    title: "Paper OPD Register vs Digital Clinic Software: What's the Real Cost Difference?",
    category: "Clinic Operations",
    angle: "Paper registers cost ₹0 upfront but ₹80,000+ per month in hidden no-show and inefficiency costs",
    status: "pending",
  },
  {
    id: 34,
    keyword: "Practo alternative India 2026 no commission",
    title: "5 Practo Alternatives for Indian Doctors in 2026 That Charge 0% Commission",
    category: "Software Comparisons",
    angle: "Doctors are waking up to Practo's 20% take — here are the independence-first alternatives",
    status: "pending",
  },
  {
    id: 35,
    keyword: "SMS reminder vs WhatsApp reminder for patients India",
    title: "SMS vs WhatsApp Patient Reminders: Why WhatsApp Wins Every Time for Indian Clinics",
    category: "Automation & Technology",
    angle: "SMS has 20% open rate. WhatsApp has 98%. The maths is the strategy.",
    status: "pending",
  },
  {
    id: 36,
    keyword: "clinic management software free vs paid India",
    title: "Free vs Paid Clinic Management Software in India: What You Get and What You Lose",
    category: "Software Comparisons",
    angle: "Free tools cost more in hidden operational losses than a ₹1,999/quarter paid tool",
    status: "pending",
  },
  {
    id: 37,
    keyword: "Lybrate vs Practo vs Doctor Diary clinic software India",
    title: "Lybrate vs Practo vs Doctor Diary: The Definitive Indian Clinic Software Comparison 2026",
    category: "Software Comparisons",
    angle: "Three-way comparison from a doctor's perspective — features, pricing, commissions, ownership",
    status: "pending",
  },
  {
    id: 38,
    keyword: "solo doctor vs clinic chain software needs India",
    title: "Solo Doctor Practice vs Multi-Doctor Clinic: How Software Needs Differ in India",
    category: "Clinic Operations",
    angle: "A 3-room multi-specialty OPD has different automation needs than a solo GP — this guide clarifies both",
    status: "pending",
  },
  {
    id: 39,
    keyword: "government hospital vs private clinic software India",
    title: "Why Private Clinic Software in India Must Solve What Government Hospital Systems Never Will",
    category: "Clinic Operations",
    angle: "Private practice software needs are fundamentally different — patient experience vs throughput",
    status: "pending",
  },
  {
    id: 40,
    keyword: "clinic app India Android iPhone best for doctor",
    title: "Best Clinic Management App for Android and iPhone — For Indian Doctors in 2026",
    category: "Software Comparisons",
    angle: "Most clinic apps are either too complex or too weak — here's what doctors actually need on mobile",
    status: "pending",
  },

  // ─── HOW-TO GUIDES (10 articles) ──────────────────────────────────────────
  {
    id: 41,
    keyword: "how to set up digital queue system for clinic India",
    title: "How to Set Up a Digital Queue System for Your Clinic in India (5-Minute Guide)",
    category: "How-To Guides",
    angle: "Step-by-step: from paper tokens to live WhatsApp queue in one afternoon",
    status: "pending",
  },
  {
    id: 42,
    keyword: "how to get patients to book appointments online India",
    title: "How to Get Patients to Book Online Instead of Calling Your Clinic (India Guide)",
    category: "How-To Guides",
    angle: "Patient behaviour change strategy — WhatsApp links, QR codes, and onboarding tactics",
    status: "pending",
  },
  {
    id: 43,
    keyword: "how to send WhatsApp reminders to clinic patients India",
    title: "How to Send Automated WhatsApp Reminders to Clinic Patients in India (Zero Code)",
    category: "How-To Guides",
    angle: "Non-technical setup guide — from zero to automated reminders in one hour",
    status: "pending",
  },
  {
    id: 44,
    keyword: "how to reduce patient no shows clinic India",
    title: "How to Reduce Patient No-Shows at Your Clinic by 40% — The Proven 5-Step System",
    category: "Clinic Growth & Revenue",
    angle: "Practical, data-backed system: reminders + confirmation + queue transparency = near-zero no-shows",
    status: "pending",
  },
  {
    id: 45,
    keyword: "how to get more patients to your clinic India",
    title: "How to Get More Patients to Your Clinic Without Paying Practo Commission in 2026",
    category: "Clinic Growth & Revenue",
    angle: "Google visibility + own clinic URL + WhatsApp booking = your own patient acquisition engine",
    status: "pending",
  },
  {
    id: 46,
    keyword: "how to create digital prescription clinic India",
    title: "How to Create and Send Digital Prescriptions to Patients in India (No Printer Needed)",
    category: "How-To Guides",
    angle: "Digital Rx reduces transcription errors, saves paper, and reaches patients on WhatsApp instantly",
    status: "pending",
  },
  {
    id: 47,
    keyword: "how to manage staff in medical clinic India software",
    title: "How to Manage Clinic Staff, Reception, and Assistants with One Software in India",
    category: "Clinic Operations",
    angle: "Role-based access for doctors, receptionists, and staff — what a modern clinic dashboard looks like",
    status: "pending",
  },
  {
    id: 48,
    keyword: "how to get Google reviews for clinic India",
    title: "How to Get 100+ Genuine Google Reviews for Your Clinic in India (The Ethical Way)",
    category: "Clinic Growth & Revenue",
    angle: "Post-visit automated Google review requests — the tactic that builds trust without gaming",
    status: "pending",
  },
  {
    id: 49,
    keyword: "how to transition clinic from paper to digital India",
    title: "How to Migrate Your Clinic From Paper to Digital Without Disrupting Your Patients",
    category: "How-To Guides",
    angle: "Change management guide — staff training, patient communication, and 2-week transition plan",
    status: "pending",
  },
  {
    id: 50,
    keyword: "how to measure clinic revenue growth India KPIs",
    title: "The 6 KPIs Every Independent Doctor in India Must Track to Grow Clinic Revenue",
    category: "Clinic Growth & Revenue",
    angle: "No-show rate, slot utilisation, patient retention, review score — measurable clinic health metrics",
    status: "pending",
  },

  // ─── UAE & MIDDLE EAST EXPANSION (15 articles) ─────────────────────────────
  {
    id: 51,
    keyword: "best clinic management software Dubai UAE",
    title: "Best Clinic Management Software for Private Clinics in Dubai (2026 Guide)",
    category: "Software Comparisons",
    city: "Dubai",
    angle: "Dubai clinics face high operational costs — how WhatsApp booking and zero-commission software maximizes ROI",
    internalLink: "/for/general-physician/dubai",
    status: "pending",
  },
  {
    id: 52,
    keyword: "dermatology clinic software Dubai AED booking",
    title: "How Dermatology Clinics in Dubai Cut No-Shows on High-Ticket Aesthetic Procedures",
    category: "Specialty Practice Growth",
    specialty: "Dermatology",
    city: "Dubai",
    angle: "Aesthetic consultations in Jumeirah & Downtown Dubai lose AED 500-2000 per no-show — how WhatsApp reminders stop it",
    internalLink: "/for/dermatology/dubai",
    status: "pending",
  },
  {
    id: 53,
    keyword: "medical center appointment system Abu Dhabi",
    title: "The Modern Medical Center Appointment System for Clinics in Abu Dhabi",
    category: "Clinic Operations",
    city: "Abu Dhabi",
    angle: "Managing multi-specialty polyclinics in Abu Dhabi without waiting room congestion",
    internalLink: "/for/general-physician/abu-dhabi",
    status: "pending",
  },
  {
    id: 54,
    keyword: "dental appointment software Sharjah UAE",
    title: "Dental Clinic Software in Sharjah: Streamlining WhatsApp Booking & Patient Retention",
    category: "Specialty Practice Growth",
    specialty: "Dental",
    city: "Sharjah",
    angle: "Sharjah dental practices scaling multi-session orthodontic and cosmetic appointment schedules",
    internalLink: "/for/dental/sharjah",
    status: "pending",
  },
  {
    id: 55,
    keyword: "pediatric clinic vaccination reminders Dubai",
    title: "How Pediatricians in Dubai Automate Immunization Reminders via WhatsApp",
    category: "Specialty Practice Growth",
    specialty: "Pediatrics",
    city: "Dubai",
    angle: "Expat families in Dubai demand proactive mobile updates for child vaccination schedules",
    internalLink: "/for/pediatrics/dubai",
    status: "pending",
  },
  {
    id: 56,
    keyword: "polyclinic queue management software UAE",
    title: "Polyclinic Queue Management in UAE: How to Eliminate Lobby Crowding",
    category: "Clinic Operations",
    city: "Dubai",
    angle: "Multi-specialty centers across Dubai & Abu Dhabi reducing front-desk workload with digital tokens",
    internalLink: "/for/general-physician/dubai",
    status: "pending",
  },
  {
    id: 57,
    keyword: "WhatsApp doctor appointment booking UAE",
    title: "Why WhatsApp Appointment Booking is Dominating Healthcare in Dubai & UAE",
    category: "Automation & Technology",
    city: "Dubai",
    angle: "UAE has 99% WhatsApp penetration — why mobile-first clinic booking converts 3x better than apps",
    internalLink: "/for/general-physician/dubai",
    status: "pending",
  },
  {
    id: 58,
    keyword: "physiotherapy clinic package tracking Dubai",
    title: "Physiotherapy Clinics in Dubai: Stopping Mid-Course Patient Drop-Outs",
    category: "Specialty Practice Growth",
    specialty: "Physiotherapy",
    city: "Dubai",
    angle: "10-session physio packages in UAE suffer from drop-out — automated WhatsApp check-ins preserve revenue",
    internalLink: "/for/physiotherapy/dubai",
    status: "pending",
  },
  {
    id: 59,
    keyword: "aesthetic surgery patient reminders Dubai",
    title: "Plastic & Cosmetic Surgery Clinics in Dubai: Premium Pre-Op & Post-Op Patient Journeys",
    category: "Specialty Practice Growth",
    specialty: "Plastic Surgery",
    city: "Dubai",
    angle: "High-net-worth aesthetic patients in Dubai expect VIP digital workflows from consultation to recovery",
    internalLink: "/for/plastic-surgery/dubai",
    status: "pending",
  },
  {
    id: 60,
    keyword: "obstetrics gynecology appointment system Abu Dhabi",
    title: "Privacy-First Appointment Systems for Gynecology Practices in Abu Dhabi",
    category: "Specialty Practice Growth",
    specialty: "Gynecology",
    city: "Abu Dhabi",
    angle: "Protecting patient privacy and streamlining prenatal checkups in Abu Dhabi clinics",
    internalLink: "/for/obstetrics-gynecology/abu-dhabi",
    status: "pending",
  },

  // ─── RECEPTIONIST & HIGH-INTENT CLINIC LEADERSHIP (10 articles) ────────────
  {
    id: 61,
    keyword: "receptionist script clinic patient calls India",
    title: "The Ultimate Receptionist Script & Automation Playbook for Indian Medical OPDs",
    category: "Front-Desk Workflows",
    angle: "How front-desk staff can answer 50+ phone calls automatically without losing patient goodwill",
    status: "pending",
  },
  {
    id: 62,
    keyword: "clinic revenue calculation formula doctor India",
    title: "How to Calculate Your Clinic's True Revenue Leakage (Free Doctor Calculator)",
    category: "Clinic Growth & Revenue",
    angle: "A step-by-step mathematical breakdown of no-show costs, delayed follow-ups, and unbooked slots",
    status: "pending",
  },
  {
    id: 63,
    keyword: "how to train clinic receptionist on software India",
    title: "How to Train Your Clinic Receptionist on Digital Systems in 30 Minutes",
    category: "Front-Desk Workflows",
    angle: "Zero-stress onboarding guide for senior or non-tech receptionist staff",
    status: "pending",
  },
  {
    id: 64,
    keyword: "multi specialty OPD software India",
    title: "Multi-Specialty OPD Software in India: Managing 5+ Doctors on One Single Screen",
    category: "Clinic Operations",
    angle: "Polyclinic doctors sharing rooms, reception, and billing — how unified software prevents clashes",
    status: "pending",
  },
  {
    id: 65,
    keyword: "patient loyalty program doctor clinic India",
    title: "How to Build a Patient Retention Engine for Your Private Consultation Practice",
    category: "Clinic Growth & Revenue",
    angle: "Turning one-off consultations into lifetime family health relationships with automated follow-ups",
    status: "pending",
  },
];

/** Returns all pending topics in order */
export function getPendingTopics(): BlogTopic[] {
  return BLOG_TOPICS.filter((t) => t.status === "pending");
}

/** Returns a topic by ID */
export function getTopicById(id: number): BlogTopic | undefined {
  return BLOG_TOPICS.find((t) => t.id === id);
}
