export const PRICING_PLANS = {
  quarterly: {
    id: "quarterly",
    name: "Quarterly",
    price: "₹1,499",
    basePrice: 1499,
    duration: "per 3 months",
    shortDuration: "/ 3 months",
    description: "Perfect for single clinics getting started.",
    features: [
      "14-Day Unlimited Free Trial",
      "Unlimited Patients & Appointments",
      "Free Premium Starter Kit (Worth ₹1,999)",
      "Smart WhatsApp & SMS Ready",
      "Executive Analytics & Queue Manager",
    ],
    popular: false,
  },
  yearly: {
    id: "yearly",
    name: "Annual",
    price: "₹4,999",
    basePrice: 4999,
    duration: "per year",
    shortDuration: "/ 12 months",
    description: "Maximum ROI for established doctor practices.",
    features: [
      "14-Day Unlimited Free Trial",
      "Everything in Quarterly",
      "Dedicated Account Manager",
      "Area Exclusivity Rights Locked",
      "Priority WhatsApp Support Channel",
    ],
    popular: true,
  },
  enterprise: {
    id: "enterprise",
    name: "Enterprise & Polyclinics",
    price: "Custom",
    basePrice: 0,
    duration: "starting ₹14,999/yr",
    shortDuration: "/ custom",
    description: "For multi-doctor clinics, polyclinics & hospitals.",
    features: [
      "Multi-Doctor Queue & Staff Switcher",
      "Role-Based Access (Doctors, Reception, Pharmacy)",
      "Custom WhatsApp Sender Branding",
      "White-Glove Concierge Data Migration",
      "24/7 VIP Priority Phone Support",
    ],
    popular: false,
  },
} as const;

export type PlanId = keyof typeof PRICING_PLANS;
